import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
<nav className="flex justify-between p-4 bg-zinc-900 text-white">
  <div className="font-bold">FlightMods</div>

  <div className="flex gap-4">
    <a href="/">Home</a>
    <a href="/addons">Addons</a>
    <a href="/login">Login</a>
    <a href="/register">Register</a>
  </div>
</nav>